# Setup
title: Khs Jekyll
baseurl: ""
url : "https://github.com/kohs116/kohs116.github.io"
permalink: pretty



author:
  name: Ko Huisu
  email: kohs116@inu.ac.kr

# Custom vars
version: 3.0.0

# Navbar page list
nav:
  - title: Blog
    url: /archive

  - title: About
    url: /about
